# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dbscan_train <- function(df, eps, minPts, dis_metric = "euclidean") {
    .Call(`_Marble_dbscan_train`, df, eps, minPts, dis_metric)
}

dbscan_projection <- function(new_data, train_data, dbscan_cores, eps, dis_metric = "euclidean") {
    .Call(`_Marble_dbscan_projection`, new_data, train_data, dbscan_cores, eps, dis_metric)
}

dfToVecVec <- function(df) {
    .Call(`_Marble_dfToVecVec`, df)
}

euclidean_distance <- function(pointA, pointB) {
    .Call(`_Marble_euclidean_distance`, pointA, pointB)
}

mahalanobis_distance <- function(pointA, pointB, cov_mat) {
    .Call(`_Marble_mahalanobis_distance`, pointA, pointB, cov_mat)
}

